version: "3.8"
services:
  db:
    image: "postgres:14"
    command: postgres -c stats_temp_directory=/tmp
    hostname: "${POSTGRES_HOST}"
    container_name: cypress_ror_db
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
  web:
    env_file:
      - ./.env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${ROR_PORT} -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${ROR_HOST_PORT}:${ROR_PORT}"
    depends_on:
      - db
