version: "3.8"
services:
  db:
    image: "postgres:14"
    command: postgres -c stats_temp_directory=/tmp
    hostname: "${POSTGRES_HOST}"
    container_name: cypress_ror_db
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:rw
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
  web:
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}"
      - "ROR_ENV=${ROR_ENV}"
      - "ROR_HOST_PORT=${ROR_HOST_PORT}"
      - "ROR_PORT=${ROR_PORT}"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${ROR_PORT} -e ${ROR_ENV} -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${ROR_HOST_PORT}:${ROR_PORT}"
    depends_on:
      - db
